#pragma config(Sensor, S1,     button1,        sensorEV3_Touch)
#pragma config(Sensor, S3,     sonar,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     button2,        sensorEV3_Touch)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		while(sensorValue(sonar) >= 30)
		{
			motor(left)=60;
			motor(right)=55;
		}
		motor(left)=60;
		motor(right)=-25;

	}
}
